sudo: required

language: bash

services:
  - docker

env:
  - PHP_RUNTIME='php:7.2-cli' PHPUNIT_OPTS='--coverage-clover=coverage.clover'
  - PHP_RUNTIME='hhvm/hhvm:nightly'

matrix:
  allow_failures:
    - env: PHP_RUNTIME='hhvm/hhvm:nightly'
  fast_finish: true

install:
  - ./dockerfile.sh | tee /dev/tty | docker build -t msgpack -

script:
  - docker run --rm -v $(pwd):/msgpack -w /msgpack -e PHPUNIT_OPTS="$PHPUNIT_OPTS" msgpack

after_script:
  - if [[ -f coverage.clover ]]; then
      curl -sSOL https://scrutinizer-ci.com/ocular.phar &&
      docker run --rm -v $(pwd):/coverage -w /coverage msgpack php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
    fi
